# Generated by Django 3.2.9 on 2021-11-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Try',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('short_paragraph', models.CharField(max_length=10000)),
                ('news', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='pics')),
            ],
        ),
    ]
