# Generated by Django 3.2.9 on 2021-11-16 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='try',
            name='Categoary',
            field=models.CharField(blank='True', default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='try',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
