# Generated by Django 3.2.9 on 2021-11-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211116_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='try',
            old_name='news',
            new_name='news_paragraph_1',
        ),
        migrations.AddField(
            model_name='try',
            name='news_paragraph_2',
            field=models.TextField(blank='True', default=''),
        ),
        migrations.AddField(
            model_name='try',
            name='news_paragraph_3',
            field=models.TextField(blank='True', default=''),
        ),
    ]
