# Generated by Django 3.2.9 on 2021-11-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_join_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='E_Magazine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('magazine_cover', models.ImageField(upload_to='e-magzine')),
                ('magazine', models.FileField(upload_to='e-magzine')),
            ],
        ),
    ]
