# Generated by Django 3.2.9 on 2021-11-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_e_magazine'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_magazine',
            name='Year',
            field=models.CharField(blank='True', default='', max_length=100),
        ),
    ]
