# Generated by Django 3.2.9 on 2021-11-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_e_magazine_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Try',
            new_name='News',
        ),
    ]
