# Generated by Django 3.2.9 on 2021-11-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_news_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e_magazine',
            name='Year',
        ),
    ]
